Issue 6
WSU-CEG-6110-4410/Remainders-Craft pull request #17
Opened 2022-04-07 15:53 UTC by fosterj14

Created the doxygen config file. This will generate documentation and place it in the src folder when ran from the src directory. We may want to integrate this into CMake at a later point in order to automate the documentation process when building the project.

2022-04-07 17:06 UTC, lukemoore495 requested changes

2022-04-07 17:06 UTC, lukemoore495 commented on Doxyfile
> +PROJECT_NAME           = "Craft"
Maybe we ought to call the Project "Remainders-Craft" to match the repository.

2022-04-07 17:06 UTC, lukemoore495 commented on Doxyfile
> +PROJECT_BRIEF          =
It might be good to link the GitHub repository's ReadMe here or some brief description of the project.

2022-04-09 19:24 UTC, fosterj14 commented on Doxyfile
> +PROJECT_NAME           = "Craft"
Changed the name

2022-04-09 19:25 UTC, fosterj14 commented on Doxyfile
> +PROJECT_BRIEF          =
Added info from the ReadMe

2022-04-12 00:01 UTC, TiMcCall approved these changes
These changes have been reviewed and look to be in good order.

2022-04-12 00:07 UTC, lukemoore495 approved these changes

2022-04-12 16:08 UTC, merged